from data.dict_lang import Lang
from . import Lang
from . import info_of_bot
from . import choiceLanguage
from . import language
from . import lang_dec
from . import start
from . import translator
from . import inline_mode